# Etapa 1: Identificação da faixa temporal com melhor distribuição de valores

## 1. Importando libs

In [1]:
!pip3 install pandas
!pip3 install numpy

Requirement already satisfied: pandas in /home/joca/.local/lib/python3.8/site-packages (1.0.5)
Requirement already satisfied: pytz>=2017.2 in /usr/lib/python3/dist-packages (from pandas) (2019.3)
Requirement already satisfied: numpy>=1.13.3 in /home/joca/.local/lib/python3.8/site-packages (from pandas) (1.19.0)
Requirement already satisfied: python-dateutil>=2.6.1 in /usr/lib/python3/dist-packages (from pandas) (2.7.3)
Requirement already satisfied: numpy in /home/joca/.local/lib/python3.8/site-packages (1.19.0)

In [2]:
import pandas as pd
import zipfile

## 2. Carregando o dataframe com todos os dados de todos os países e da faixa temporal de anos.

In [9]:
zf = zipfile.ZipFile('../data/Edstats_csv.zip')
text_files = zf.infolist()
df_todos_paises = pd.DataFrame()
for csv_file in text_files:        
    if csv_file.filename == 'EdStatsData.csv':
        print("Abrindo o arquivo",csv_file.filename)
        df_todos_paises = pd.read_csv(zf.open(csv_file.filename))
        break

if df_todos_paises.empty:
    exit("Erro ao ler o arquivo 'EdStatsData.csv' que fica dentro do 'Edstats_csv.zip' na pasta 'data'.")
else:
    print("Arquivo 'EdStatsData.csv' carregado com sucesso.")

Abrindo o arquivo EdStatsData.csv
Arquivo 'EdStatsData.csv' carregado com sucesso.

## 3. Selecionar as linhas referentes aos indicadores relevantes ao tema relacionado à mensuração de infectados com HIV.
Previamente, de acordo com o tema e os objetivos do trabalho de conclusão de curso, foram selecionados indicadores socioeconomicos para responder questionamentos e realizar análises e previsões. Sendo esses considerados os indicadores relevantes.

### 3.1. Carregar códigos dos indicadores relacionados à AIDS.

In [10]:
df_indicadores_relevantes = pd.read_csv('../data/codigos_indicadores_relevantes_aids.csv')

df_indicadores_relevantes.columns = ['Indicator Code']

        Indicator Code
0       NY.GDP.MKTP.CD
1       IT.NET.USER.P2
2          SP.POP.GROW
3       SL.UEM.TOTL.ZS
4    SE.XPD.TOTL.GD.ZS
5       UIS.LP.AG15T24
6   UIS.ILLPOP.AG25T64
7          SE.PRM.TCHR
8          UIS.ROFST.1
9    SE.PRM.ENRL.TC.ZS
10         SE.PRM.TENR

### 3.2. Remover as colunas que não serão utilizadas na mensuração da faixa temporal.

In [5]:
df_faixa_temporal_indicadores_relevantes = df_todos_paises.loc[df_todos_paises['Indicator Code'].isin(df_indicadores_relevantes['Indicator Code'])]

df_faixa_temporal_indicadores_relevantes = df_faixa_temporal_indicadores_relevantes.drop(['Country Name', 'Country Code', 'Indicator Name', 'Indicator Code'], axis=1)
df_faixa_temporal_indicadores_relevantes.index = range(df_faixa_temporal_indicadores_relevantes.shape[0])

df_faixa_temporal_indicadores_relevantes.fillna(0, inplace = True)

### 3.3. Identificar a faixa temporal, relacionada aos indicadores relevantes ao tema, de acordo com o preenchimento dos dados no dataset "EdStatsData.csv".

In [6]:
df_anos_com_dados_vazios = df_faixa_temporal_indicadores_relevantes.loc[:, df_faixa_temporal_indicadores_relevantes.isin([0]).mean() >= .6]

df_intervalo_anos_preenchidos = df_faixa_temporal_indicadores_relevantes.drop(list(df_anos_com_dados_vazios.columns), axis=1)

df_intervalo_anos_preenchidos.head()

,1991,1992,1993,1994,1995,1996,1997,1998,1999,2000,...,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015
0,7.260284e+01,7.003272e+01,7.046482e+01,7.264568e+01,7.181176e+01,7.390351e+01,7.442520e+01,7.511082e+01,7.625432e+01,7.724568e+01,...,8.268551e+01,8.328034e+01,8.401187e+01,8.419596e+01,8.521200e+01,8.524514e+01,8.610167e+01,8.551194e+01,85.320152,0.0
1,4.368056e+11,4.678345e+11,4.732993e+11,4.842611e+11,5.200493e+11,5.744682e+11,6.092942e+11,5.874948e+11,6.341186e+11,7.260126e+11,...,1.399823e+12,1.638669e+12,2.079571e+12,1.791753e+12,2.097884e+12,2.487905e+12,2.744381e+12,2.853079e+12,0.000000,0.0
2,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,...,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000,0.0
3,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,...,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000,0.0
4,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,1.702505e-02,3.776069e-02,1.310456e-01,2.616151e-01,5.985821e-01,1.139541e+00,...,1.165465e+01,1.420590e+01,1.859353e+01,2.297369e+01,2.674725e+01,2.970776e+01,3.401422e+01,3.686860e+01,0.000000,0.0

### 3.4. Identificar a faixa temporal, relacionada aos indicadores relevantes ao tema, de acordo com preenchimento dos dados no dataset "Epidemic transition metrics_Trend of new HIV infections.csv".

In [7]:
df_infeccoes_hiv = pd.read_csv('../data/Epidemic transition metrics_Trend of new HIV infections.csv')

df_infeccoes_hiv.head()

,Country,2010,2010_lower,2010_upper,2011,2011_lower,2011_upper,2012,2012_lower,2012_upper,...,2017,2017_lower,2017_upper,2018,2018_lower,2018_upper,2019,2019_lower,2019_upper,2019.1
0,Afghanistan,<1000,<500,1800,<1000,<500,2000,<1000,<500,2300,...,1300,<500,4800,1400,<500,5100,1500,<500,5500,116
1,Albania,<200,<100,<200,<200,<100,<200,<200,<100,<500,...,<100,<100,<500,<100,<100,<500,<100,<100,<500,-23
2,Algeria,1200,<1000,1700,1300,<1000,1900,1400,<1000,2100,...,1900,<1000,3300,2000,<500,3600,2100,<500,4100,83
3,Angola,26 000,21 000,31 000,27 000,22 000,32 000,27 000,22 000,32 000,...,27 000,20 000,34 000,27 000,19 000,35 000,26 000,18 000,34 000,-2
4,Argentina,5700,4600,7500,6000,4700,7900,6100,4800,7900,...,6100,4400,8200,5700,4100,8100,5900,4300,8500,3

### 3.5. Exportar a faixa temporal em "lista_anos_aids.csv" com a interseção do período de anos dos dois datasets mencionados acima.
O ano que iniciará essa faixa de tempo será o de 2010, vide o resultado da célula anterior que exibe algumas linhas do dataset "Epidemic transition metrics_Trend of new HIV infections.csv" e percebe-se que este inicia-se em 2010.

Antes de escolher o ano final dessa faixa temporal, é preciso analisar a qualidade dos dados de 2014 e 2015 do dataset "EdStatsData.csv". Com esse valor, será possível determinar que a lista de anos a ser utilizada nas próximas etapas será a de 2010 até 2014.

In [8]:
if (df_intervalo_anos_preenchidos['2016'].mean().round(2) > df_intervalo_anos_preenchidos['2017'].mean().round(2)):
       
    anos = pd.Series([2010, 2011, 2012, 2013, 2014])
    anos.name = 'Year'
    anos.to_csv('../data/lista_anos_aids.csv', index = False)
    print('O intervalo de anos será até 2014')
    
else:
    anos = pd.Series([2010, 2011, 2012, 2013, 2014, 2015])
    anos.name = 'Year'
    anos.to_csv('../data/lista_anos_aids.csv', index = False)
    print('O intervalo de anos será até 2015')

KeyError: '2016'